name: Documentation

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.10        
      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Create Docs
        run: |
             mkdir public
             cp -r "${{github.workspace}}/docs/" public/docs
             julia -e 'push!(LOAD_PATH, "${{github.workspace}}"); using VueJS; include("${{github.workspace}}/docs/make.jl")'
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
